### PR TITLE
Flag off uglifyify

### PR DESCRIPTION
**Pull request by toddself**
Add a flag to prevent uglifyify from running on the assets to let people run
es6 code more easily.

### CODE REVIEW

**Comment by yoshuawuyts** [comment]
Oh, the way I was thinking to do this would be to set `uglify` as a boolean, and default to `true` - never been a fan of the negate-flags haha. E.g. the API would become:
```sh
$ bankai start --uglify=false index.js
```

**Comment by yoshuawuyts** [comment]
Oh, also this would need to be documented in the `bin.js` help text and `readme.md`

**Comment by toddself** [comment]
Oh good point.  The flag has been changed to be like `watch`, and the README is updated now with a note about ES5 syntax.

**Comment by yoshuawuyts** [comment]
`v7.1.0` :tada:

**Pull request merged**
