### PR TITLE
feat(bankai): simplify

### PR DESCRIPTION
**Pull request by yoshuawuyts**
This paves the way for some more fancy things; much needed spring cleaning

### changes
- change JS API (no more event emitters)
- change CLI API (less options, use subargs)
- remove a lot of code
- unvendor deps
- remove clunky tests

### todo
- [x] patch `watchify-request` to detect if `res` exists
- [x] fix bug where `bankai` build doesn't exit when done

---
### CLI API
```txt
  Usage:
    $ bankai <command> [options]

  Commands:
    <default>                      Run 'bankai start'
    start <filename>               Start a bankai server
    build <filename> <directory>   Compile and export files to a directory

    Options:
      -c, --css=<subargs>     Pass subarguments to sheetify
      -h, --help              Print usage
      -j, --js=<subargs>      Pass subarguments to browserify
      -o, --open=<browser>    Open html in a browser [default: system default]
      -O, --optimize          Optimize assets served by bankai [default: false]
      -p, --port=<n>          Bind bankai to <n> [default: 8080]

  Examples:
    $ bankai index.js -p 8080            # start bankai on port 8080
    $ bankai index.js --open             # open html in the browser
    $ bankai -c [ -u sheetify-cssnext ]  # use cssnext in sheetify
    $ bankai -j [ -t brfs ]              # use brfs in browserify
    $ bankai build index.js dist/        # compile and export to dist/
    $ bankai build -O index.js dist/     # optimize compiled files
```

### JS API
```js
const bankai = require('bankai')
const http = require('http')
const path = require('path')

const clientPath = path.join(__dirname, 'client.js')
const assets = bankai(clientPath)

http.createServer((req, res) => {
  switch (req.url) {
    case '/': return assets.html(req, res).pipe(res)
    case '/bundle.js': return assets.js(req, res).pipe(res)
    case '/bundle.css': return assets.css(req, res).pipe(res)
    default: return (res.statusCode = 404 && res.end('404 not found'))
  }
}).listen(8080)
```

### CODE REVIEW

**Comment by bcomnes** [comment]
Live reload?

**Comment by yoshuawuyts** [comment]
Not yet, minor patch on top of this

**Comment by yoshuawuyts** [comment]
tho it's looking pretty good; should be easy to add hey:
- https://github.com/bengourley/hot-rld/blob/master/server.js
- https://github.com/bengourley/choo-resume

**Comment by aknuds1** [comment]
@yoshuawuyts Is Ben Gourley's work an alternative to my live reload patch?

**Comment by yoshuawuyts** [comment]
@aknuds1 yup; like I said in the beginning - using `hot module reload` stuff is preferable over using `tiny-lr` and friends not only because it's simpler - it's also a nicer workflow and less strain on the CPU

**Comment by aknuds1** [comment]
@yoshuawuyts Ah, I must've missed what you said about hot module reload.

**Comment by bcomnes** [comment]
I've had some frustrations with HMR in the past with redux/react apps.  I'm open to see how it works with choo though.

**Comment by yoshuawuyts** [comment]
@bcomnes never tried it properly before; real curious how it'll turn out - if anything having the option will be sw-eet

**Comment by yoshuawuyts** [comment]
all is good - merging!

**Pull request merged**
